MONGODB_HOST: mongodb.backend-alb-{{ env }}.mitha.fun 
REDIS_HOST: redis.backend-alb-{{ env }}.mitha.fun 
MYSQL_HOST: mysql.backend-alb-{{ env }}.mitha.fun 
CATALOGUE_HOST : catalogue.backend-alb-{{ env }}.mitha.fun 
CART_HOST : cart.backend-alb-{{ env }}.mitha.fun 
USER_HOST : user.backend-alb-{{ env }}.mitha.fun 
RABBITMQ_HOST : rabbitmq.backend-alb-{{ env }}.mitha.fun 
SHIPPING_HOST: shipping.backend-alb-{{ env }}.mitha.fun